#!/usr/bin/env python3

import pathlib

import networkx as nx

from benchmark import Network


def convert_transitive(network: Network, cutoff: int) -> Network:
    new_network = Network(network.end)

    stops = set()
    for conn in network.conns:
        for node_id in [conn.from_node_id, conn.to_node_id]:
            if node_id not in stops:
                node = network.nodes[node_id]
                new_network.add_node(
                    node_id,
                    node.latitude, node.longitude,
                    True,
                )
                stops.add(node_id)

        new_network.add_conn(
            conn.trip_id,
            conn.from_node_id, conn.to_node_id,
            conn.departure_time, conn.arrival_time,
        )

    paths = [(path.node_a_id, path.node_b_id, path.duration) for path in network.paths]
    G = nx.Graph()
    G.add_weighted_edges_from(paths)

    for stop in stops:
        if stop not in G:
            print(f'Warning: stop node {stop} is not present in paths')
            continue
        durations = nx.single_source_shortest_path_length(G, stop, cutoff)
        for other, duration in durations.items():
            if other not in stops:
                continue
            new_network.add_path(stop, other, duration)

    G.clear()
    return new_network


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('input', type=pathlib.Path)
    parser.add_argument('output', type=pathlib.Path)
    parser.add_argument('cutoff', type=int, nargs='?', default=900)
    args = parser.parse_args()

    network = Network.read(args.input)
    print(f'Before: {network}')
    network = convert_transitive(network, args.cutoff)
    print(f'After: {network}')
    network.write(args.output)
